/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package electionspoo.gui;

import electionspoo.beans.ElectorBean;
import java.awt.Image;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.time.LocalDate;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.Icon;

/**
 *
 * @author Tiago
 */
public class GUICandidate extends javax.swing.JDialog {

    /**
     * Creates new form GUIElector
     */
    public GUICandidate(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        GUICandBtnSave = new javax.swing.JButton();
        GUICandBtnOpen = new javax.swing.JButton();
        GUICandBtnNew = new javax.swing.JButton();
        GUICandBtnSearch = new javax.swing.JButton();
        GUICandBtnClose = new javax.swing.JButton();
        GUICandPanelCandList = new javax.swing.JScrollPane();
        GUICandList = new javax.swing.JList<>();
        GUICandLabelCandList = new javax.swing.JLabel();
        GUICandPanelBottomNav = new javax.swing.JPanel();
        GUIElectorBtnFirst = new javax.swing.JButton();
        GUIElectorBtnPrev = new javax.swing.JButton();
        GUIElectorBtnNext = new javax.swing.JButton();
        GUIElectorBtnLast = new javax.swing.JButton();
        GUICandPanelElector = new javax.swing.JPanel();
        GUICandLabelName = new javax.swing.JLabel();
        GUICandTxtBoxName = new javax.swing.JTextField();
        GUICandLabelInitials = new javax.swing.JLabel();
        GUICandTxtBoxInitials = new javax.swing.JTextField();
        GUICandBtnNewCand = new javax.swing.JButton();
        GUICandBtnDeleteCand = new javax.swing.JButton();
        GUICandPanelImage = new javax.swing.JPanel();
        GUICandLabel2Image = new javax.swing.JLabel();
        GUICandLabelPhoto = new javax.swing.JLabel();
        GUICandBtnUp = new javax.swing.JButton();
        GUICandBtnDown = new javax.swing.JButton();
        GUICandLabelElector = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        GUICandBtnSave.setIcon(new javax.swing.ImageIcon(getClass().getResource("/electionspoo/multimedia/save_file.png"))); // NOI18N
        GUICandBtnSave.setText("Guardar");
        GUICandBtnSave.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        GUICandBtnSave.setVerifyInputWhenFocusTarget(false);
        GUICandBtnSave.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);

        GUICandBtnOpen.setIcon(new javax.swing.ImageIcon(getClass().getResource("/electionspoo/multimedia/open_file.png"))); // NOI18N
        GUICandBtnOpen.setText("Abrir");
        GUICandBtnOpen.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        GUICandBtnOpen.setVerifyInputWhenFocusTarget(false);
        GUICandBtnOpen.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);

        GUICandBtnNew.setIcon(new javax.swing.ImageIcon(getClass().getResource("/electionspoo/multimedia/newElection.png"))); // NOI18N
        GUICandBtnNew.setText("Novo");
        GUICandBtnNew.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        GUICandBtnNew.setVerifyInputWhenFocusTarget(false);
        GUICandBtnNew.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);

        GUICandBtnSearch.setIcon(new javax.swing.ImageIcon(getClass().getResource("/electionspoo/multimedia/nav_find.png"))); // NOI18N
        GUICandBtnSearch.setText("Pesquisar");
        GUICandBtnSearch.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        GUICandBtnSearch.setVerifyInputWhenFocusTarget(false);
        GUICandBtnSearch.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);

        GUICandBtnClose.setIcon(new javax.swing.ImageIcon("C:\\Users\\Tiago\\Documents\\GitHub\\electionsPOO\\electionsPOO\\src\\electionspoo\\multimedia\\exit.png")); // NOI18N
        GUICandBtnClose.setText("Sair");
        GUICandBtnClose.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        GUICandBtnClose.setVerifyInputWhenFocusTarget(false);
        GUICandBtnClose.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        GUICandBtnClose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GUICandBtnCloseActionPerformed(evt);
            }
        });

        GUICandPanelCandList.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        GUICandList.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5", "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        GUICandPanelCandList.setViewportView(GUICandList);

        GUICandLabelCandList.setText("Lista Eleitoral");

        GUICandPanelBottomNav.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        GUIElectorBtnFirst.setIcon(new javax.swing.ImageIcon(getClass().getResource("/electionspoo/multimedia/nav_first.png"))); // NOI18N

        GUIElectorBtnPrev.setIcon(new javax.swing.ImageIcon(getClass().getResource("/electionspoo/multimedia/nav_prev.png"))); // NOI18N

        GUIElectorBtnNext.setIcon(new javax.swing.ImageIcon(getClass().getResource("/electionspoo/multimedia/nav_last.png"))); // NOI18N

        GUIElectorBtnLast.setIcon(new javax.swing.ImageIcon(getClass().getResource("/electionspoo/multimedia/nav_next.png"))); // NOI18N

        javax.swing.GroupLayout GUICandPanelBottomNavLayout = new javax.swing.GroupLayout(GUICandPanelBottomNav);
        GUICandPanelBottomNav.setLayout(GUICandPanelBottomNavLayout);
        GUICandPanelBottomNavLayout.setHorizontalGroup(
            GUICandPanelBottomNavLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(GUICandPanelBottomNavLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(GUIElectorBtnFirst, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(GUIElectorBtnPrev, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 73, Short.MAX_VALUE)
                .addComponent(GUIElectorBtnLast, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(GUIElectorBtnNext, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        GUICandPanelBottomNavLayout.setVerticalGroup(
            GUICandPanelBottomNavLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(GUICandPanelBottomNavLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(GUICandPanelBottomNavLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(GUIElectorBtnNext, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(GUIElectorBtnLast, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(GUICandPanelBottomNavLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(GUIElectorBtnFirst, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(GUIElectorBtnPrev, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(13, Short.MAX_VALUE))
        );

        GUICandPanelElector.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        GUICandLabelName.setText("Nome");

        GUICandLabelInitials.setText("Sigla");

        GUICandTxtBoxInitials.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GUICandTxtBoxInitialsActionPerformed(evt);
            }
        });

        GUICandBtnNewCand.setIcon(new javax.swing.ImageIcon("C:\\Users\\Tiago\\Documents\\GitHub\\electionsPOO\\electionsPOO\\src\\electionspoo\\multimedia\\nav_add.png")); // NOI18N
        GUICandBtnNewCand.setText("Novo");
        GUICandBtnNewCand.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GUICandBtnNewCandActionPerformed(evt);
            }
        });

        GUICandBtnDeleteCand.setIcon(new javax.swing.ImageIcon(getClass().getResource("/electionspoo/multimedia/nav_delete.png"))); // NOI18N
        GUICandBtnDeleteCand.setText("Eliminar");

        GUICandPanelImage.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        GUICandLabel2Image.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        GUICandLabel2Image.setIcon(new javax.swing.ImageIcon(getClass().getResource("/electionspoo/multimedia/about.png"))); // NOI18N

        javax.swing.GroupLayout GUICandPanelImageLayout = new javax.swing.GroupLayout(GUICandPanelImage);
        GUICandPanelImage.setLayout(GUICandPanelImageLayout);
        GUICandPanelImageLayout.setHorizontalGroup(
            GUICandPanelImageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(GUICandLabel2Image, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        GUICandPanelImageLayout.setVerticalGroup(
            GUICandPanelImageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(GUICandLabel2Image, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        GUICandLabelPhoto.setText("Fotografia");

        GUICandBtnUp.setIcon(new javax.swing.ImageIcon(getClass().getResource("/electionspoo/multimedia/nav_up.png"))); // NOI18N
        GUICandBtnUp.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        GUICandBtnDown.setIcon(new javax.swing.ImageIcon(getClass().getResource("/electionspoo/multimedia/nav_down.png"))); // NOI18N
        GUICandBtnDown.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout GUICandPanelElectorLayout = new javax.swing.GroupLayout(GUICandPanelElector);
        GUICandPanelElector.setLayout(GUICandPanelElectorLayout);
        GUICandPanelElectorLayout.setHorizontalGroup(
            GUICandPanelElectorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(GUICandPanelElectorLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(GUICandPanelElectorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(GUICandTxtBoxName)
                    .addGroup(GUICandPanelElectorLayout.createSequentialGroup()
                        .addGroup(GUICandPanelElectorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(GUICandLabelName)
                            .addGroup(GUICandPanelElectorLayout.createSequentialGroup()
                                .addGroup(GUICandPanelElectorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(GUICandBtnNewCand, javax.swing.GroupLayout.DEFAULT_SIZE, 179, Short.MAX_VALUE)
                                    .addComponent(GUICandTxtBoxInitials, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(GUICandLabelInitials, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, GUICandPanelElectorLayout.createSequentialGroup()
                                        .addGap(10, 10, 10)
                                        .addGroup(GUICandPanelElectorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(GUICandBtnDown, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(GUICandBtnUp, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                .addGap(18, 18, 18)
                                .addGroup(GUICandPanelElectorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(GUICandPanelImage, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(GUICandLabelPhoto)
                                    .addComponent(GUICandBtnDeleteCand, javax.swing.GroupLayout.DEFAULT_SIZE, 175, Short.MAX_VALUE))))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        GUICandPanelElectorLayout.setVerticalGroup(
            GUICandPanelElectorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(GUICandPanelElectorLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(GUICandLabelName)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(GUICandTxtBoxName, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(GUICandPanelElectorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(GUICandLabelInitials)
                    .addComponent(GUICandLabelPhoto))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(GUICandPanelElectorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(GUICandPanelElectorLayout.createSequentialGroup()
                        .addComponent(GUICandTxtBoxInitials, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(36, 36, 36)
                        .addComponent(GUICandBtnUp, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(GUICandBtnDown, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(GUICandPanelImage, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(GUICandPanelElectorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(GUICandBtnDeleteCand, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(GUICandBtnNewCand, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        GUICandLabelElector.setText("Eleitor");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(GUICandBtnSave)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(GUICandBtnOpen)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(GUICandBtnNew)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(GUICandBtnSearch)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(GUICandBtnClose))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(GUICandLabelCandList)
                            .addComponent(GUICandPanelCandList)
                            .addComponent(GUICandPanelBottomNav, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(GUICandLabelElector)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(GUICandPanelElector, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(1, 1, 1)))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(GUICandBtnSearch, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(GUICandBtnOpen, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(GUICandBtnSave, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(GUICandBtnNew, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(GUICandBtnClose, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(GUICandLabelCandList)
                    .addComponent(GUICandLabelElector))
                .addGap(2, 2, 2)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(GUICandPanelCandList, javax.swing.GroupLayout.PREFERRED_SIZE, 411, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 24, Short.MAX_VALUE)
                        .addComponent(GUICandPanelBottomNav, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(GUICandPanelElector, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(32, 32, 32))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void GUICandBtnCloseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GUICandBtnCloseActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_GUICandBtnCloseActionPerformed

    private void GUICandBtnNewCandActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GUICandBtnNewCandActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_GUICandBtnNewCandActionPerformed

    private void GUICandTxtBoxInitialsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GUICandTxtBoxInitialsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_GUICandTxtBoxInitialsActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GUICandidate.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GUICandidate.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GUICandidate.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GUICandidate.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                GUICandidate dialog = new GUICandidate(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }
    
   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton GUICandBtnClose;
    private javax.swing.JButton GUICandBtnDeleteCand;
    private javax.swing.JButton GUICandBtnDown;
    private javax.swing.JButton GUICandBtnNew;
    private javax.swing.JButton GUICandBtnNewCand;
    private javax.swing.JButton GUICandBtnOpen;
    private javax.swing.JButton GUICandBtnSave;
    private javax.swing.JButton GUICandBtnSearch;
    private javax.swing.JButton GUICandBtnUp;
    private javax.swing.JLabel GUICandLabel2Image;
    private javax.swing.JLabel GUICandLabelCandList;
    private javax.swing.JLabel GUICandLabelElector;
    private javax.swing.JLabel GUICandLabelInitials;
    private javax.swing.JLabel GUICandLabelName;
    private javax.swing.JLabel GUICandLabelPhoto;
    private javax.swing.JList<String> GUICandList;
    private javax.swing.JPanel GUICandPanelBottomNav;
    private javax.swing.JScrollPane GUICandPanelCandList;
    private javax.swing.JPanel GUICandPanelElector;
    private javax.swing.JPanel GUICandPanelImage;
    private javax.swing.JTextField GUICandTxtBoxInitials;
    private javax.swing.JTextField GUICandTxtBoxName;
    private javax.swing.JButton GUIElectorBtnFirst;
    private javax.swing.JButton GUIElectorBtnLast;
    private javax.swing.JButton GUIElectorBtnNext;
    private javax.swing.JButton GUIElectorBtnPrev;
    // End of variables declaration//GEN-END:variables
}
