/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package electionspoo.gui;

import electionspoo.beans.ElectorBean;
import electionspoo.bo.ElectorBO;
import electionspoo.bo.ElectorBOOliveira;
import electionspoo.utils.enums.FirstNamesEnum;
import electionspoo.utils.enums.LastNamesEnum;
import java.awt.Image;
import java.io.FileNotFoundException;
import java.io.FileOutputStream;
import java.io.IOException;
import java.io.ObjectOutputStream;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.time.LocalDate;
import java.util.ArrayList;
import java.util.Date;
import java.util.GregorianCalendar;
import java.util.Random;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultListModel;
import javax.swing.Icon;
import javax.swing.JList;
import javax.swing.ListSelectionModel;

/**
 *
 * @author Tiago
 */
public class GUIElector extends javax.swing.JDialog {

    DefaultListModel<String> listaGUI = new DefaultListModel<>();

    //adiciona o ultimo eleitor criado à listaGUI
    private void addNewElectorToList(String elector) {
        GUIElectorList.setModel(listaGUI);
        listaGUI.addElement(elector);
    }

    //lista todos os electors guardados no ficheiro
    private void addElectorsToList() {
        try {
            GUIElectorList.setModel(listaGUI);
            listaGUI.removeAllElements();
            ArrayList<ElectorBean> listaElectors = ElectorBOOliveira.readFile();
            for (int i = 0; i < listaElectors.size(); i++) {

                listaGUI.addElement(listaElectors.get(i).toString());
            }

        } catch (IOException ex) {
            Logger.getLogger(GUIElector.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(GUIElector.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ParseException ex) {
            Logger.getLogger(GUIElector.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    /**
     * Creates new form GUIElector
     */
    public GUIElector(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        GUIElectorBtnSave = new javax.swing.JButton();
        GUIElectorBtnOpen = new javax.swing.JButton();
        GUIElectorBtnNew = new javax.swing.JButton();
        GUIElectorBtnSort = new javax.swing.JButton();
        GUIElectorBtnSearch = new javax.swing.JButton();
        GUIElectorBtnClose = new javax.swing.JButton();
        GUIElectorPanelElectorList = new javax.swing.JScrollPane();
        GUIElectorList = new javax.swing.JList<>();
        GUIElectorPanelBottomNav = new javax.swing.JPanel();
        GUIElectorBtnFirst = new javax.swing.JButton();
        GUIElectorBtnPrev = new javax.swing.JButton();
        GUIElectorBtnNext = new javax.swing.JButton();
        GUIElectorBtnLast = new javax.swing.JButton();
        GUIElectorPanelElector = new javax.swing.JPanel();
        GUIElectorTxtBoxName = new javax.swing.JTextField();
        GUIElectorTxtBoxCC = new javax.swing.JTextField();
        GUIElectorGender = new javax.swing.JComboBox<>();
        GUIElectorBtnNewElector = new javax.swing.JButton();
        GUIElectorBtnDeleteElector = new javax.swing.JButton();
        GUIElectorBtnRandomElector = new javax.swing.JButton();
        GUIElectorPanelImage = new javax.swing.JPanel();
        GUIElectorLabel2Image = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        GUIElectorTxtBoxBirth = new javax.swing.JTextField();
        GUIElectorTxtBoxPw = new javax.swing.JTextField();
        GUIElectorTxtBoxPw2 = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        GUIElectorBtnSave.setIcon(new javax.swing.ImageIcon(getClass().getResource("/electionspoo/multimedia/save_file.png"))); // NOI18N
        GUIElectorBtnSave.setText("Guardar");
        GUIElectorBtnSave.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        GUIElectorBtnSave.setVerifyInputWhenFocusTarget(false);
        GUIElectorBtnSave.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);

        GUIElectorBtnOpen.setIcon(new javax.swing.ImageIcon(getClass().getResource("/electionspoo/multimedia/open_file.png"))); // NOI18N
        GUIElectorBtnOpen.setText("Abrir");
        GUIElectorBtnOpen.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        GUIElectorBtnOpen.setVerifyInputWhenFocusTarget(false);
        GUIElectorBtnOpen.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);

        GUIElectorBtnNew.setIcon(new javax.swing.ImageIcon(getClass().getResource("/electionspoo/multimedia/newElection.png"))); // NOI18N
        GUIElectorBtnNew.setText("Novo");
        GUIElectorBtnNew.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        GUIElectorBtnNew.setVerifyInputWhenFocusTarget(false);
        GUIElectorBtnNew.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);

        GUIElectorBtnSort.setIcon(new javax.swing.ImageIcon(getClass().getResource("/electionspoo/multimedia/sort.png"))); // NOI18N
        GUIElectorBtnSort.setText("Ordenar");
        GUIElectorBtnSort.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        GUIElectorBtnSort.setVerifyInputWhenFocusTarget(false);
        GUIElectorBtnSort.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);

        GUIElectorBtnSearch.setIcon(new javax.swing.ImageIcon(getClass().getResource("/electionspoo/multimedia/nav_find.png"))); // NOI18N
        GUIElectorBtnSearch.setText("Pesquisar");
        GUIElectorBtnSearch.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        GUIElectorBtnSearch.setVerifyInputWhenFocusTarget(false);
        GUIElectorBtnSearch.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);

        GUIElectorBtnClose.setText("Sair");
        GUIElectorBtnClose.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        GUIElectorBtnClose.setVerifyInputWhenFocusTarget(false);
        GUIElectorBtnClose.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        GUIElectorBtnClose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GUIElectorBtnCloseActionPerformed(evt);
            }
        });

        GUIElectorPanelElectorList.setBorder(javax.swing.BorderFactory.createTitledBorder("Lista de Eleitores"));

        GUIElectorList.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                GUIElectorListValueChanged(evt);
            }
        });
        GUIElectorPanelElectorList.setViewportView(GUIElectorList);

        GUIElectorPanelBottomNav.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        GUIElectorBtnFirst.setIcon(new javax.swing.ImageIcon(getClass().getResource("/electionspoo/multimedia/nav_first.png"))); // NOI18N

        GUIElectorBtnPrev.setIcon(new javax.swing.ImageIcon(getClass().getResource("/electionspoo/multimedia/nav_prev.png"))); // NOI18N

        GUIElectorBtnNext.setIcon(new javax.swing.ImageIcon(getClass().getResource("/electionspoo/multimedia/nav_next.png"))); // NOI18N
        GUIElectorBtnNext.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GUIElectorBtnNextActionPerformed(evt);
            }
        });

        GUIElectorBtnLast.setIcon(new javax.swing.ImageIcon(getClass().getResource("/electionspoo/multimedia/nav_last.png"))); // NOI18N
        GUIElectorBtnLast.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GUIElectorBtnLastActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout GUIElectorPanelBottomNavLayout = new javax.swing.GroupLayout(GUIElectorPanelBottomNav);
        GUIElectorPanelBottomNav.setLayout(GUIElectorPanelBottomNavLayout);
        GUIElectorPanelBottomNavLayout.setHorizontalGroup(
            GUIElectorPanelBottomNavLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(GUIElectorPanelBottomNavLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(GUIElectorBtnFirst, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(GUIElectorBtnPrev, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 73, Short.MAX_VALUE)
                .addComponent(GUIElectorBtnNext, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(GUIElectorBtnLast, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        GUIElectorPanelBottomNavLayout.setVerticalGroup(
            GUIElectorPanelBottomNavLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(GUIElectorPanelBottomNavLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(GUIElectorPanelBottomNavLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(GUIElectorBtnLast, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(GUIElectorBtnNext, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(GUIElectorPanelBottomNavLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(GUIElectorBtnFirst, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(GUIElectorBtnPrev, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(13, Short.MAX_VALUE))
        );

        GUIElectorPanelElector.setBorder(javax.swing.BorderFactory.createTitledBorder("Eleitor"));

        GUIElectorTxtBoxName.setText("Teste");
        GUIElectorTxtBoxName.setBorder(javax.swing.BorderFactory.createTitledBorder("Nome"));

        GUIElectorTxtBoxCC.setText("12345678");
        GUIElectorTxtBoxCC.setBorder(javax.swing.BorderFactory.createTitledBorder("Cartão de Cidadão"));
        GUIElectorTxtBoxCC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GUIElectorTxtBoxCCActionPerformed(evt);
            }
        });

        GUIElectorGender.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "M", "F", " " }));

        GUIElectorBtnNewElector.setText("Novo");
        GUIElectorBtnNewElector.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GUIElectorBtnNewElectorActionPerformed(evt);
            }
        });

        GUIElectorBtnDeleteElector.setIcon(new javax.swing.ImageIcon(getClass().getResource("/electionspoo/multimedia/nav_delete.png"))); // NOI18N
        GUIElectorBtnDeleteElector.setText("Eliminar");
        GUIElectorBtnDeleteElector.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GUIElectorBtnDeleteElectorActionPerformed(evt);
            }
        });

        GUIElectorBtnRandomElector.setIcon(new javax.swing.ImageIcon(getClass().getResource("/electionspoo/multimedia/nav_update.png"))); // NOI18N
        GUIElectorBtnRandomElector.setText("Gerar Aleatório");
        GUIElectorBtnRandomElector.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GUIElectorBtnRandomElectorActionPerformed(evt);
            }
        });

        GUIElectorPanelImage.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        GUIElectorLabel2Image.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        GUIElectorLabel2Image.setIcon(new javax.swing.ImageIcon(getClass().getResource("/electionspoo/multimedia/about.png"))); // NOI18N

        javax.swing.GroupLayout GUIElectorPanelImageLayout = new javax.swing.GroupLayout(GUIElectorPanelImage);
        GUIElectorPanelImage.setLayout(GUIElectorPanelImageLayout);
        GUIElectorPanelImageLayout.setHorizontalGroup(
            GUIElectorPanelImageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(GUIElectorLabel2Image, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        GUIElectorPanelImageLayout.setVerticalGroup(
            GUIElectorPanelImageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(GUIElectorLabel2Image, javax.swing.GroupLayout.DEFAULT_SIZE, 281, Short.MAX_VALUE)
        );

        jLabel8.setText("Idade..");

        GUIElectorTxtBoxBirth.setText("06/06/2001");
        GUIElectorTxtBoxBirth.setBorder(javax.swing.BorderFactory.createTitledBorder("Data de Nascimento"));

        GUIElectorTxtBoxPw.setText("123");
        GUIElectorTxtBoxPw.setBorder(javax.swing.BorderFactory.createTitledBorder("Password"));
        GUIElectorTxtBoxPw.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GUIElectorTxtBoxPwActionPerformed(evt);
            }
        });

        GUIElectorTxtBoxPw2.setText("123");
        GUIElectorTxtBoxPw2.setBorder(javax.swing.BorderFactory.createTitledBorder("Confirmar Password"));

        javax.swing.GroupLayout GUIElectorPanelElectorLayout = new javax.swing.GroupLayout(GUIElectorPanelElector);
        GUIElectorPanelElector.setLayout(GUIElectorPanelElectorLayout);
        GUIElectorPanelElectorLayout.setHorizontalGroup(
            GUIElectorPanelElectorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(GUIElectorPanelElectorLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(GUIElectorPanelElectorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(GUIElectorTxtBoxName)
                    .addGroup(GUIElectorPanelElectorLayout.createSequentialGroup()
                        .addGroup(GUIElectorPanelElectorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(GUIElectorBtnNewElector, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(GUIElectorTxtBoxCC, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(GUIElectorGender, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(GUIElectorTxtBoxBirth, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(GUIElectorTxtBoxPw, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(GUIElectorTxtBoxPw2, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(GUIElectorBtnRandomElector, javax.swing.GroupLayout.DEFAULT_SIZE, 179, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(GUIElectorPanelElectorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(GUIElectorPanelImage, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel8)
                            .addComponent(GUIElectorBtnDeleteElector, javax.swing.GroupLayout.DEFAULT_SIZE, 175, Short.MAX_VALUE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        GUIElectorPanelElectorLayout.setVerticalGroup(
            GUIElectorPanelElectorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(GUIElectorPanelElectorLayout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(GUIElectorTxtBoxName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(11, 11, 11)
                .addGroup(GUIElectorPanelElectorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(GUIElectorPanelElectorLayout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(GUIElectorPanelImage, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(GUIElectorPanelElectorLayout.createSequentialGroup()
                        .addComponent(GUIElectorTxtBoxCC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(20, 20, 20)
                        .addComponent(GUIElectorGender, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(GUIElectorTxtBoxBirth, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(26, 26, 26)
                        .addComponent(GUIElectorTxtBoxPw, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(33, 33, 33)
                        .addComponent(GUIElectorTxtBoxPw2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(GUIElectorBtnRandomElector)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(GUIElectorPanelElectorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(GUIElectorBtnDeleteElector, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(GUIElectorBtnNewElector, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(GUIElectorBtnSave)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(GUIElectorBtnOpen)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(GUIElectorBtnNew)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(GUIElectorBtnSort)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(GUIElectorBtnSearch)
                        .addGap(18, 359, Short.MAX_VALUE)
                        .addComponent(GUIElectorBtnClose))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(GUIElectorPanelElectorList)
                            .addComponent(GUIElectorPanelBottomNav, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(GUIElectorPanelElector, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(1, 1, 1)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(GUIElectorBtnSearch, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(GUIElectorBtnSort, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(GUIElectorBtnOpen, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(GUIElectorBtnSave, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(GUIElectorBtnNew, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(GUIElectorBtnClose, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(GUIElectorPanelElectorList, javax.swing.GroupLayout.PREFERRED_SIZE, 443, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, Short.MAX_VALUE)
                        .addComponent(GUIElectorPanelBottomNav, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(GUIElectorPanelElector, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void GUIElectorBtnCloseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GUIElectorBtnCloseActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_GUIElectorBtnCloseActionPerformed

    private void GUIElectorTxtBoxCCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GUIElectorTxtBoxCCActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_GUIElectorTxtBoxCCActionPerformed

    private void GUIElectorBtnNewElectorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GUIElectorBtnNewElectorActionPerformed

        try {
            SimpleDateFormat sdf = new SimpleDateFormat("dd/mm/yyyy");
            ElectorBean temp = new ElectorBean(GUIElectorTxtBoxName.getText(), Integer.parseInt(GUIElectorTxtBoxCC.getText()), GUIElectorGender.getSelectedItem().toString().charAt(0), sdf.parse(GUIElectorTxtBoxBirth.getText()), GUIElectorTxtBoxPw.getText(), GUIElectorLabel2Image.getIcon());
            //ElectorBO.saveElectorOnFile(temp);
            try {
                ElectorBOOliveira.saveToFile(temp);
                addNewElectorToList(temp.toString());
            } catch (FileNotFoundException ex) {
                Logger.getLogger(GUIElector.class.getName()).log(Level.SEVERE, null, ex);
            } catch (ClassNotFoundException ex) {
                Logger.getLogger(GUIElector.class.getName()).log(Level.SEVERE, null, ex);
            }

        } catch (ParseException | IOException ex) {
            Logger.getLogger(GUIElector.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_GUIElectorBtnNewElectorActionPerformed

    private void GUIElectorTxtBoxPwActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GUIElectorTxtBoxPwActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_GUIElectorTxtBoxPwActionPerformed

    private void GUIElectorBtnRandomElectorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GUIElectorBtnRandomElectorActionPerformed
        // TODO add your handling code here:
        Random rd = new Random();
        StringBuilder nome = new StringBuilder();
        GregorianCalendar gc = new GregorianCalendar();
        SimpleDateFormat sdf = new SimpleDateFormat("dd/mm/yyyy");

        FirstNamesEnum fne = ElectorBO.getRandomFirstName(rd);
        nome.append(fne.toString()).append(" ");
        nome.append(ElectorBO.getRandomLastName(rd).toString());
        int cc = ElectorBO.getRandom8DigitNumber(rd);
        char gender = fne.getGender();
        gc = ElectorBO.getRandomBirthDate(gc);
        int password = ElectorBO.getRandom8DigitNumber(rd);

        try {
            //ElectorBO.saveElectorOnFile(new ElectorBean(nome.toString(), cc, gender, gc.getTime(), String.valueOf(password)));
            ElectorBean temp = new ElectorBean(nome.toString(), cc, gender, gc.getTime(), String.valueOf(password));
            try {
                ElectorBOOliveira.saveToFile(temp);
            } catch (FileNotFoundException ex) {
                Logger.getLogger(GUIElector.class.getName()).log(Level.SEVERE, null, ex);
            } catch (ClassNotFoundException ex) {
                Logger.getLogger(GUIElector.class.getName()).log(Level.SEVERE, null, ex);
            } catch (ParseException ex) {
                Logger.getLogger(GUIElector.class.getName()).log(Level.SEVERE, null, ex);
            }
            addNewElectorToList(temp.toString());
        } catch (IOException ex) {
            Logger.getLogger(GUIElector.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_GUIElectorBtnRandomElectorActionPerformed

    private void GUIElectorBtnDeleteElectorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GUIElectorBtnDeleteElectorActionPerformed
        addElectorsToList();
    }//GEN-LAST:event_GUIElectorBtnDeleteElectorActionPerformed

    private void GUIElectorBtnLastActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GUIElectorBtnLastActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_GUIElectorBtnLastActionPerformed

    private void GUIElectorBtnNextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GUIElectorBtnNextActionPerformed

    }//GEN-LAST:event_GUIElectorBtnNextActionPerformed

    private void GUIElectorListValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_GUIElectorListValueChanged
        // TODO add your handling code here:
        //System.out.println("First index: " + evt.getFirstIndex());
        //System.out.println(", Last index: " + evt.getLastIndex());
        boolean adjust = evt.getValueIsAdjusting();
        //System.out.println(", Adjusting? " + adjust);
        if (!adjust) {
            try {
                ArrayList<ElectorBean> listaElectors = ElectorBOOliveira.readFile();
                JList list = (JList) evt.getSource();
                int selections[] = list.getSelectedIndices();
                Object selectionValues[] = list.getSelectedValues();
                for (int i = 0, n = selections.length; i < n; i++) {
                    if (i == 0) {
                        //System.out.println(" Selections: ");
                    }
                    //System.out.println("I=" + selections[i] + "/" + selectionValues[i] + " ");
                    //System.out.println("I=" + selections[i] + "-" + listaElectors.get(selections[i]).getName());
                    
                    SimpleDateFormat formatter1 = new SimpleDateFormat("dd/mm/yyyy");
                    String date = formatter1.format(listaElectors.get(selections[i]).getBirthDate());
                    
                    GUIElectorTxtBoxName.setText(listaElectors.get(selections[i]).getName());
                    GUIElectorTxtBoxCC.setText(""+listaElectors.get(selections[i]).getCC());
                    
                    if(listaElectors.get(selections[i]).getGender() == ('M')){
                        GUIElectorGender.setSelectedIndex(0);
                    } else {
                        GUIElectorGender.setSelectedIndex(1);
                    }
                    
                    GUIElectorTxtBoxBirth.setText(date);
                    GUIElectorTxtBoxPw.setText(listaElectors.get(selections[i]).getPassword());
                    GUIElectorTxtBoxPw2.setText(listaElectors.get(selections[i]).getPassword());
                    
                }
            } catch (IOException ex) {
                Logger.getLogger(GUIElector.class.getName()).log(Level.SEVERE, null, ex);
            } catch (ClassNotFoundException ex) {
                Logger.getLogger(GUIElector.class.getName()).log(Level.SEVERE, null, ex);
            } catch (ParseException ex) {
                Logger.getLogger(GUIElector.class.getName()).log(Level.SEVERE, null, ex);
            }

        }
    }//GEN-LAST:event_GUIElectorListValueChanged

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GUIElector.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GUIElector.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GUIElector.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GUIElector.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        try {
            ElectorBOOliveira.createFile();
        } catch (IOException ex) {
            Logger.getLogger(GUIElector.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ParseException ex) {
            Logger.getLogger(GUIElector.class.getName()).log(Level.SEVERE, null, ex);
        }


        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                GUIElector dialog = new GUIElector(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);

            }
        });
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton GUIElectorBtnClose;
    private javax.swing.JButton GUIElectorBtnDeleteElector;
    private javax.swing.JButton GUIElectorBtnFirst;
    private javax.swing.JButton GUIElectorBtnLast;
    private javax.swing.JButton GUIElectorBtnNew;
    private javax.swing.JButton GUIElectorBtnNewElector;
    private javax.swing.JButton GUIElectorBtnNext;
    private javax.swing.JButton GUIElectorBtnOpen;
    private javax.swing.JButton GUIElectorBtnPrev;
    private javax.swing.JButton GUIElectorBtnRandomElector;
    private javax.swing.JButton GUIElectorBtnSave;
    private javax.swing.JButton GUIElectorBtnSearch;
    private javax.swing.JButton GUIElectorBtnSort;
    private javax.swing.JComboBox<String> GUIElectorGender;
    private javax.swing.JLabel GUIElectorLabel2Image;
    private javax.swing.JList<String> GUIElectorList;
    private javax.swing.JPanel GUIElectorPanelBottomNav;
    private javax.swing.JPanel GUIElectorPanelElector;
    private javax.swing.JScrollPane GUIElectorPanelElectorList;
    private javax.swing.JPanel GUIElectorPanelImage;
    private javax.swing.JTextField GUIElectorTxtBoxBirth;
    private javax.swing.JTextField GUIElectorTxtBoxCC;
    private javax.swing.JTextField GUIElectorTxtBoxName;
    private javax.swing.JTextField GUIElectorTxtBoxPw;
    private javax.swing.JTextField GUIElectorTxtBoxPw2;
    private javax.swing.JLabel jLabel8;
    // End of variables declaration//GEN-END:variables
}
