/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package electionspoo.gui;


import electionspoo.beans.candidate.CandidateList;
import electionspoo.beans.election.ElectionManager;
import electionspoo.beans.elector.ElectorList;
import electionspoo.utils.MainUtils;
import java.io.File;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFileChooser;


/**
 *
 * @author Tiago
 */
public class GUIResults extends javax.swing.JDialog {

    
    private void updateGUILists() {
        MainUtils.listaGUIElector.removeAllElements();
        MainUtils.listaGUICandidate.removeAllElements();
        MainUtils.listaGUIResults.removeAllElements();
        
        for (int i = 0; i < ElectorList.getList().size(); i++) {
            MainUtils.listaGUIElector.addElement(ElectorList.getGUIListLine(ElectionManager.getElection().getElectorList().get(i)));
        }
        for (int i = 0; i < CandidateList.getList().size(); i++) {
            MainUtils.listaGUICandidate.addElement(CandidateList.getGUIListLine(ElectionManager.getElection().getCandidateList().get(i)));
        }
        for (int i = 0; i < CandidateList.getList().size(); i++) {
            MainUtils.listaGUIResults.addElement(CandidateList.getResultsGUILine(ElectionManager.getElection().getCandidateList().get(i)));
        }
        
    }
    /**
     * Creates new form GUIResults
     */
    public GUIResults(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        
        GUIResultsEleitorList.setModel(MainUtils.listaGUIElector);
        GUIResultsCandidatesList.setModel(MainUtils.listaGUICandidate);
        GUIResultsList.setModel(MainUtils.listaGUIResults);
        
        GUIResultsNomeEleicao.setText(ElectionManager.getElection().getName());
        GUIResultsEleicaoDataInicio.setText(ElectionManager.getElection().getStartDate());
        GUIResultsEleicaoDataFim.setText(ElectionManager.getElection().getStartDate());
        
        updateGUILists();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        GUIResultsBtnOpen = new javax.swing.JButton();
        GUIResultsBtnClose = new javax.swing.JButton();
        Votantes = new javax.swing.JTabbedPane();
        GUIResultsPanelGraficos = new javax.swing.JPanel();
        GUIResultsBtnOpenGraficos = new javax.swing.JButton();
        GUIResultsPanelResults = new javax.swing.JPanel();
        GUIResultsList = new javax.swing.JList<>();
        GUIResultsPanelVoters = new javax.swing.JPanel();
        GUIResultsSearch = new javax.swing.JButton();
        GUIUtilizadorEleitorSearch = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        GUIResultsEleitorList = new javax.swing.JList<>();
        GUIResultsPanelCandidates = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        GUIResultsCandidatesList = new javax.swing.JList<>();
        GUIResultsPanelElection = new javax.swing.JPanel();
        GUIResultsNomeEleicao = new javax.swing.JTextField();
        GUIResultsEleicaoDataInicio = new javax.swing.JTextField();
        GUIResultsEleicaoDataFim = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        GUIResultsBtnOpen.setIcon(new javax.swing.ImageIcon(getClass().getResource("/electionspoo/multimedia/open_file.png"))); // NOI18N
        GUIResultsBtnOpen.setText("Abrir");
        GUIResultsBtnOpen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GUIResultsBtnOpenActionPerformed(evt);
            }
        });

        GUIResultsBtnClose.setIcon(new javax.swing.ImageIcon(getClass().getResource("/electionspoo/multimedia/exit.png"))); // NOI18N
        GUIResultsBtnClose.setText("Sair");
        GUIResultsBtnClose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GUIResultsBtnCloseActionPerformed(evt);
            }
        });

        GUIResultsBtnOpenGraficos.setText("ABRIR GRÁFICO");
        GUIResultsBtnOpenGraficos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GUIResultsBtnOpenGraficosActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout GUIResultsPanelGraficosLayout = new javax.swing.GroupLayout(GUIResultsPanelGraficos);
        GUIResultsPanelGraficos.setLayout(GUIResultsPanelGraficosLayout);
        GUIResultsPanelGraficosLayout.setHorizontalGroup(
            GUIResultsPanelGraficosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(GUIResultsPanelGraficosLayout.createSequentialGroup()
                .addGap(94, 94, 94)
                .addComponent(GUIResultsBtnOpenGraficos, javax.swing.GroupLayout.PREFERRED_SIZE, 524, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(132, Short.MAX_VALUE))
        );
        GUIResultsPanelGraficosLayout.setVerticalGroup(
            GUIResultsPanelGraficosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(GUIResultsPanelGraficosLayout.createSequentialGroup()
                .addGap(100, 100, 100)
                .addComponent(GUIResultsBtnOpenGraficos, javax.swing.GroupLayout.PREFERRED_SIZE, 263, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(104, Short.MAX_VALUE))
        );

        Votantes.addTab("Gráfico", GUIResultsPanelGraficos);

        GUIResultsList.setBorder(javax.swing.BorderFactory.createTitledBorder("Resultados"));

        javax.swing.GroupLayout GUIResultsPanelResultsLayout = new javax.swing.GroupLayout(GUIResultsPanelResults);
        GUIResultsPanelResults.setLayout(GUIResultsPanelResultsLayout);
        GUIResultsPanelResultsLayout.setHorizontalGroup(
            GUIResultsPanelResultsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(GUIResultsList, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 750, Short.MAX_VALUE)
        );
        GUIResultsPanelResultsLayout.setVerticalGroup(
            GUIResultsPanelResultsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(GUIResultsList, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 467, Short.MAX_VALUE)
        );

        Votantes.addTab("Resultados", GUIResultsPanelResults);

        GUIResultsSearch.setIcon(new javax.swing.ImageIcon(getClass().getResource("/electionspoo/multimedia/nav_find.png"))); // NOI18N
        GUIResultsSearch.setText("Pesquisar");
        GUIResultsSearch.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        GUIResultsSearch.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        GUIResultsSearch.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        GUIResultsSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GUIResultsSearchActionPerformed(evt);
            }
        });

        GUIUtilizadorEleitorSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GUIUtilizadorEleitorSearchActionPerformed(evt);
            }
        });

        jScrollPane1.setBorder(javax.swing.BorderFactory.createTitledBorder("Lista Eleitoral"));
        jScrollPane1.setViewportView(GUIResultsEleitorList);

        javax.swing.GroupLayout GUIResultsPanelVotersLayout = new javax.swing.GroupLayout(GUIResultsPanelVoters);
        GUIResultsPanelVoters.setLayout(GUIResultsPanelVotersLayout);
        GUIResultsPanelVotersLayout.setHorizontalGroup(
            GUIResultsPanelVotersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(GUIResultsPanelVotersLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(GUIResultsPanelVotersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(GUIResultsPanelVotersLayout.createSequentialGroup()
                        .addComponent(jScrollPane1)
                        .addContainerGap())
                    .addGroup(GUIResultsPanelVotersLayout.createSequentialGroup()
                        .addComponent(GUIResultsSearch, javax.swing.GroupLayout.DEFAULT_SIZE, 126, Short.MAX_VALUE)
                        .addGap(18, 18, 18)
                        .addComponent(GUIUtilizadorEleitorSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 594, javax.swing.GroupLayout.PREFERRED_SIZE))))
        );
        GUIResultsPanelVotersLayout.setVerticalGroup(
            GUIResultsPanelVotersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(GUIResultsPanelVotersLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(GUIResultsPanelVotersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(GUIResultsSearch)
                    .addComponent(GUIUtilizadorEleitorSearch, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 355, Short.MAX_VALUE)
                .addContainerGap())
        );

        Votantes.addTab("Votantes", GUIResultsPanelVoters);

        jScrollPane2.setBorder(javax.swing.BorderFactory.createTitledBorder("Lista de Candidatos"));
        jScrollPane2.setViewportView(GUIResultsCandidatesList);

        javax.swing.GroupLayout GUIResultsPanelCandidatesLayout = new javax.swing.GroupLayout(GUIResultsPanelCandidates);
        GUIResultsPanelCandidates.setLayout(GUIResultsPanelCandidatesLayout);
        GUIResultsPanelCandidatesLayout.setHorizontalGroup(
            GUIResultsPanelCandidatesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2)
        );
        GUIResultsPanelCandidatesLayout.setVerticalGroup(
            GUIResultsPanelCandidatesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 467, Short.MAX_VALUE)
        );

        Votantes.addTab("Candidatos", GUIResultsPanelCandidates);

        GUIResultsNomeEleicao.setBorder(javax.swing.BorderFactory.createTitledBorder("Nome"));
        GUIResultsNomeEleicao.setEnabled(false);

        GUIResultsEleicaoDataInicio.setBorder(javax.swing.BorderFactory.createTitledBorder("Data de Início"));
        GUIResultsEleicaoDataInicio.setEnabled(false);

        GUIResultsEleicaoDataFim.setBorder(javax.swing.BorderFactory.createTitledBorder("Data de Fim"));
        GUIResultsEleicaoDataFim.setEnabled(false);

        jLabel4.setBorder(javax.swing.BorderFactory.createTitledBorder("Fotografia"));

        javax.swing.GroupLayout GUIResultsPanelElectionLayout = new javax.swing.GroupLayout(GUIResultsPanelElection);
        GUIResultsPanelElection.setLayout(GUIResultsPanelElectionLayout);
        GUIResultsPanelElectionLayout.setHorizontalGroup(
            GUIResultsPanelElectionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(GUIResultsPanelElectionLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(GUIResultsPanelElectionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(GUIResultsNomeEleicao)
                    .addGroup(GUIResultsPanelElectionLayout.createSequentialGroup()
                        .addGroup(GUIResultsPanelElectionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(GUIResultsEleicaoDataInicio, javax.swing.GroupLayout.DEFAULT_SIZE, 163, Short.MAX_VALUE)
                            .addComponent(GUIResultsEleicaoDataFim))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, 551, Short.MAX_VALUE)))
                .addContainerGap())
        );
        GUIResultsPanelElectionLayout.setVerticalGroup(
            GUIResultsPanelElectionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(GUIResultsPanelElectionLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(GUIResultsNomeEleicao, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(GUIResultsPanelElectionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(GUIResultsPanelElectionLayout.createSequentialGroup()
                        .addComponent(GUIResultsEleicaoDataInicio, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(GUIResultsEleicaoDataFim, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 256, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(132, Short.MAX_VALUE))
        );

        Votantes.addTab("Eleição", GUIResultsPanelElection);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addComponent(GUIResultsBtnOpen, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(GUIResultsBtnClose, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(Votantes)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(GUIResultsBtnOpen, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(GUIResultsBtnClose, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(Votantes)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void GUIUtilizadorEleitorSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GUIUtilizadorEleitorSearchActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_GUIUtilizadorEleitorSearchActionPerformed

    private void GUIResultsSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GUIResultsSearchActionPerformed
        // TODO add your handling code here:
        String textToSearch = GUIUtilizadorEleitorSearch.getText();

        int index;

        index = ElectorList.searchElectorByName(textToSearch);
        if (!(MainUtils.isNullOrEmpty(String.valueOf(index)))) {
            GUIResultsEleitorList.setSelectedIndex(index);
        } else {
            index = ElectorList.searchElectorByCC(textToSearch);
            if (!(MainUtils.isNullOrEmpty(String.valueOf(index)))) {
                GUIResultsEleitorList.setSelectedIndex(index);
            } else {
                System.out.println("Não há registos a encontrar para a string: " + textToSearch);
            }
        }
    }//GEN-LAST:event_GUIResultsSearchActionPerformed

    private void GUIResultsBtnOpenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GUIResultsBtnOpenActionPerformed
        // TODO add your handling code here:
        
        try {
            JFileChooser fileChooser = new JFileChooser();
            ElectionManager electionManager = new ElectionManager();
            fileChooser.setCurrentDirectory(new File(System.getProperty("user.dir")));
            int result = fileChooser.showOpenDialog(fileChooser);
            if (result == JFileChooser.APPROVE_OPTION) {
                String selectedFile = fileChooser.getSelectedFile().getAbsolutePath();
                electionManager.load(selectedFile);
                GUIResultsNomeEleicao.setText(ElectionManager.getElection().getName());
                GUIResultsEleicaoDataInicio.setText(ElectionManager.getElection().getStartDate());
                GUIResultsEleicaoDataFim.setText(ElectionManager.getElection().getEndDate());
                updateGUILists();
            }
        } catch (IOException | ClassNotFoundException ex) {
            Logger.getLogger(GUIElector.class.getName()).log(Level.SEVERE, null, ex);
        } catch (Exception ex) {
            Logger.getLogger(GUICandidate.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_GUIResultsBtnOpenActionPerformed

    private void GUIResultsBtnCloseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GUIResultsBtnCloseActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_GUIResultsBtnCloseActionPerformed

    private void GUIResultsBtnOpenGraficosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GUIResultsBtnOpenGraficosActionPerformed
        // TODO add your handling code here:
          try {
              dispose();
            GUIResultsStatistics dialog = new GUIResultsStatistics(ElectionManager.getElection());
            dialog.setVisible(true);
        } catch (Exception ex) {
            ex.printStackTrace();
        }
    }//GEN-LAST:event_GUIResultsBtnOpenGraficosActionPerformed

   
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GUIResults.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GUIResults.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GUIResults.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GUIResults.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                GUIResults dialog = new GUIResults(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton GUIResultsBtnClose;
    private javax.swing.JButton GUIResultsBtnOpen;
    private javax.swing.JButton GUIResultsBtnOpenGraficos;
    private javax.swing.JList<String> GUIResultsCandidatesList;
    private javax.swing.JTextField GUIResultsEleicaoDataFim;
    private javax.swing.JTextField GUIResultsEleicaoDataInicio;
    private javax.swing.JList<String> GUIResultsEleitorList;
    private javax.swing.JList<String> GUIResultsList;
    private javax.swing.JTextField GUIResultsNomeEleicao;
    private javax.swing.JPanel GUIResultsPanelCandidates;
    private javax.swing.JPanel GUIResultsPanelElection;
    private javax.swing.JPanel GUIResultsPanelGraficos;
    private javax.swing.JPanel GUIResultsPanelResults;
    private javax.swing.JPanel GUIResultsPanelVoters;
    private javax.swing.JButton GUIResultsSearch;
    private javax.swing.JTextField GUIUtilizadorEleitorSearch;
    private javax.swing.JTabbedPane Votantes;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    // End of variables declaration//GEN-END:variables
}
