/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package electionspoo.gui;

import electionspoo.beans.candidate.CandidateList;
import electionspoo.beans.election.ElectionManager;
import electionspoo.beans.elector.ElectorList;
import electionspoo.utils.MainUtils;
import java.io.File;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;

/**
 *
 * @author Tiago
 */
public class GUIVote extends javax.swing.JDialog {

    
    private void updateGUIList() {
        MainUtils.listaGUIElector.removeAllElements();
        for (int i = 0; i < ElectorList.getList().size(); i++) {
            MainUtils.listaGUIElector.addElement(ElectorList.getGUIListLine(ElectionManager.getElection().getElectorList().get(i)));
        }

    }
    /**
     * Creates new form Vote
     */
    public GUIVote(java.awt.Frame parent, boolean modal) throws Exception {
        super(parent, modal);
        initComponents();
      
        ElectionManager elec = new ElectionManager();
        elec.save(MainUtils.electionFilePath);
        
        
        GuiVoteElectorList.setModel(MainUtils.listaGUIElector);
        if(ElectionManager.getElection()!=null){
            GuiVoteEleicaoNome.setText(ElectionManager.getElection().getName());
        GuiVoteEleicaoDataInicio.setText(ElectionManager.getElection().getStartDate());
        GuiVoteEleicaoDataFim.setText(ElectionManager.getElection().getStartDate());
        }
        
        
        updateGUIList();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        GUIVoteCCElector = new javax.swing.JTextField();
        GUIVoteAutenticationElectorPhoto = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        GuiVotePassword = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        GuiVoteSearchField = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        GuiVoteElectorList = new javax.swing.JList<>();
        GuiVoteElectorPhoto = new javax.swing.JLabel();
        InfoLabelAboutElector = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        GuiVoteEleicaoNome = new javax.swing.JTextField();
        GuiVoteEleicaoDataInicio = new javax.swing.JTextField();
        GuiVoteEleicaoDataFim = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        GUIVoteCCElector.setBorder(javax.swing.BorderFactory.createTitledBorder("Cartão de Cidadão"));
        GUIVoteCCElector.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GUIVoteCCElectorActionPerformed(evt);
            }
        });

        GUIVoteAutenticationElectorPhoto.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        GUIVoteAutenticationElectorPhoto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/electionspoo/multimedia/election.png"))); // NOI18N
        GUIVoteAutenticationElectorPhoto.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        GuiVotePassword.setBorder(javax.swing.BorderFactory.createTitledBorder("Password"));
        GuiVotePassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GuiVotePasswordActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(GUIVoteCCElector, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 410, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(GUIVoteAutenticationElectorPhoto, javax.swing.GroupLayout.DEFAULT_SIZE, 404, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel1))
                    .addComponent(GuiVotePassword))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(GUIVoteCCElector, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(GUIVoteAutenticationElectorPhoto, javax.swing.GroupLayout.DEFAULT_SIZE, 407, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(GuiVotePassword, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jTabbedPane1.addTab("Autenticação", jPanel1);

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/electionspoo/multimedia/nav_find.png"))); // NOI18N
        jButton1.setText("Pesquisar");
        jButton1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton1.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        jButton1.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        GuiVoteSearchField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GuiVoteSearchFieldActionPerformed(evt);
            }
        });

        jScrollPane1.setBorder(javax.swing.BorderFactory.createTitledBorder("Lista Eleitoral"));

        GuiVoteElectorList.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                GuiVoteElectorListValueChanged(evt);
            }
        });
        jScrollPane1.setViewportView(GuiVoteElectorList);

        GuiVoteElectorPhoto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/electionspoo/multimedia/menu_electos.png"))); // NOI18N
        GuiVoteElectorPhoto.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 410, Short.MAX_VALUE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jButton1)
                        .addGap(18, 18, 18)
                        .addComponent(GuiVoteSearchField))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(GuiVoteElectorPhoto, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(InfoLabelAboutElector)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(GuiVoteSearchField))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 349, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(GuiVoteElectorPhoto))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(46, 46, 46)
                        .addComponent(InfoLabelAboutElector)))
                .addContainerGap(30, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Eleitores", jPanel2);

        GuiVoteEleicaoNome.setEditable(false);
        GuiVoteEleicaoNome.setBorder(javax.swing.BorderFactory.createTitledBorder("Nome"));
        GuiVoteEleicaoNome.setEnabled(false);

        GuiVoteEleicaoDataInicio.setEditable(false);
        GuiVoteEleicaoDataInicio.setBorder(javax.swing.BorderFactory.createTitledBorder("Data de Início"));
        GuiVoteEleicaoDataInicio.setEnabled(false);

        GuiVoteEleicaoDataFim.setEditable(false);
        GuiVoteEleicaoDataFim.setBorder(javax.swing.BorderFactory.createTitledBorder("Data de Fim"));
        GuiVoteEleicaoDataFim.setEnabled(false);

        jLabel4.setBorder(javax.swing.BorderFactory.createTitledBorder("Fotografia"));

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/electionspoo/multimedia/open_file.png"))); // NOI18N
        jButton2.setText("Abrir");
        jButton2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton2.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(GuiVoteEleicaoNome)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(GuiVoteEleicaoDataInicio)
                            .addComponent(GuiVoteEleicaoDataFim)
                            .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, 163, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, 235, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(GuiVoteEleicaoNome, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(GuiVoteEleicaoDataInicio, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(GuiVoteEleicaoDataFim, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(45, 45, 45)
                        .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 256, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(241, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Eleição", jPanel3);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        try {
            JFileChooser fileChooser = new JFileChooser();
            ElectionManager electionManager = new ElectionManager();
            fileChooser.setCurrentDirectory(new File(System.getProperty("user.dir")));
            int result = fileChooser.showOpenDialog(fileChooser);
            if (result == JFileChooser.APPROVE_OPTION) {
                String selectedFile = fileChooser.getSelectedFile().getAbsolutePath();
                electionManager.load(selectedFile);
                GuiVoteEleicaoNome.setText(ElectionManager.getElection().getName());
                GuiVoteEleicaoDataInicio.setText(ElectionManager.getElection().getStartDate());
                GuiVoteEleicaoDataFim.setText(ElectionManager.getElection().getEndDate());
                updateGUIList();
            }
        } catch (IOException | ClassNotFoundException ex) {
            Logger.getLogger(GUIElector.class.getName()).log(Level.SEVERE, null, ex);
        } catch (Exception ex) {
            Logger.getLogger(GUICandidate.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void GuiVoteSearchFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GuiVoteSearchFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_GuiVoteSearchFieldActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        String textToSearch = GuiVoteSearchField.getText();

        int index;

        index = ElectorList.searchElectorByName(textToSearch);
        if (!(MainUtils.isNullOrEmpty(String.valueOf(index)))) {
            GuiVoteElectorList.setSelectedIndex(index);
        } else {
            index = ElectorList.searchElectorByCC(textToSearch);
            if (!(MainUtils.isNullOrEmpty(String.valueOf(index)))) {
                GuiVoteElectorList.setSelectedIndex(index);
            } else {
                System.out.println("Não há registos a encontrar para a string: " + textToSearch);
            }
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void GuiVoteElectorListValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_GuiVoteElectorListValueChanged
        // TODO add your handling code here:
        
        int selections[] = GuiVoteElectorList.getSelectedIndices();
        if(selections.length>0){
            InfoLabelAboutElector.setText(ElectorList.getGUIListLine(ElectorList.getList().get(selections[0])));
            GUIVoteCCElector.setText(String.valueOf(ElectorList.getList().get(selections[0]).getCC()));
            //foto to label
            if (ElectorList.getList().get(selections[0]).getPhoto() != null) {
                GuiVoteElectorPhoto.setIcon(MainUtils.resizeIcon(ElectorList.getList().get(selections[0]).getPhoto(), GuiVoteElectorPhoto.getWidth(), GuiVoteElectorPhoto.getHeight()));
                GUIVoteAutenticationElectorPhoto.setIcon(MainUtils.resizeIcon(ElectorList.getList().get(selections[0]).getPhoto(), GUIVoteAutenticationElectorPhoto.getWidth(), GUIVoteAutenticationElectorPhoto.getHeight()));
            } else {
                 GuiVoteElectorPhoto.setIcon(MainUtils.resizeIcon(new ImageIcon(getClass().getResource("/electionspoo/multimedia/person.png")), GuiVoteElectorPhoto.getWidth(), GuiVoteElectorPhoto.getHeight()));
                GUIVoteAutenticationElectorPhoto.setIcon(MainUtils.resizeIcon(new ImageIcon(getClass().getResource("/electionspoo/multimedia/person.png")), GUIVoteAutenticationElectorPhoto.getWidth(), GUIVoteAutenticationElectorPhoto.getHeight()));
            } 
        }
        
    }//GEN-LAST:event_GuiVoteElectorListValueChanged

    private void GUIVoteCCElectorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GUIVoteCCElectorActionPerformed
        // TODO add your handling code here:
        
        int index = ElectorList.searchElectorByCC(GUIVoteCCElector.getText());
        
        InfoLabelAboutElector.setText(ElectorList.getGUIListLine(ElectorList.getList().get(index)));
        GUIVoteCCElector.setText(String.valueOf(ElectorList.getList().get(index).getCC()));
        //foto to label
        if (ElectorList.getList().get(index).getPhoto() != null) {
            GuiVoteElectorPhoto.setIcon(MainUtils.resizeIcon(ElectorList.getList().get(index).getPhoto(), GuiVoteElectorPhoto.getWidth(), GuiVoteElectorPhoto.getHeight()));
            GUIVoteAutenticationElectorPhoto.setIcon(MainUtils.resizeIcon(ElectorList.getList().get(index).getPhoto(), GUIVoteAutenticationElectorPhoto.getWidth(), GUIVoteAutenticationElectorPhoto.getHeight()));
        } else {
            GuiVoteElectorPhoto.setIcon(MainUtils.resizeIcon(new ImageIcon(getClass().getResource("/electionspoo/multimedia/person.png")), GuiVoteElectorPhoto.getWidth(), GuiVoteElectorPhoto.getHeight()));
            GUIVoteAutenticationElectorPhoto.setIcon(MainUtils.resizeIcon(new ImageIcon(getClass().getResource("/electionspoo/multimedia/person.png")), GUIVoteAutenticationElectorPhoto.getWidth(), GUIVoteAutenticationElectorPhoto.getHeight()));
        } 
        
    }//GEN-LAST:event_GUIVoteCCElectorActionPerformed

    private void GuiVotePasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GuiVotePasswordActionPerformed
        // TODO add your handling code here:
        int index = ElectorList.searchElectorByCC(GUIVoteCCElector.getText());
        String electorPassword = ElectorList.getList().get(index).getPassword();
        String userInputPassword = GuiVotePassword.getText();
        
        if(!ElectorList.getList().get(index).isVoted()){
            if(electorPassword.equals(userInputPassword)){
                try {
                    // TODO add your handling code here:
                    GUIUtilizador dialog = new GUIUtilizador(ElectorList.getList().get(index));
                    dialog.setVisible(true);
                    dispose();
                } catch (Exception ex) {
                    Logger.getLogger(GUIMainMenu.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        }else{
            System.out.println("Já Votou");
        }
    }//GEN-LAST:event_GuiVotePasswordActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GUIVote.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GUIVote.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GUIVote.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GUIVote.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                GUIVote dialog = null;
                try {
                    dialog = new GUIVote(new javax.swing.JFrame(), true);
                } catch (Exception ex) {
                    Logger.getLogger(GUIVote.class.getName()).log(Level.SEVERE, null, ex);
                }
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel GUIVoteAutenticationElectorPhoto;
    private javax.swing.JTextField GUIVoteCCElector;
    private javax.swing.JList<String> GuiVoteElectorList;
    private javax.swing.JLabel GuiVoteElectorPhoto;
    private javax.swing.JTextField GuiVoteEleicaoDataFim;
    private javax.swing.JTextField GuiVoteEleicaoDataInicio;
    private javax.swing.JTextField GuiVoteEleicaoNome;
    private javax.swing.JTextField GuiVotePassword;
    private javax.swing.JTextField GuiVoteSearchField;
    private javax.swing.JLabel InfoLabelAboutElector;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTabbedPane jTabbedPane1;
    // End of variables declaration//GEN-END:variables
}
